### ISSUE TITLE
IRect.h uses std::min/max without <algorithm> include

### ISSUE THREAD

**Issue by mmozeiko** [Dawoodoz/DFPSR#13]
https://github.com/Dawoodoz/DFPSR/blob/master/Source/DFPSR/math/IRect.h#L56

**Comment by Dawoodoz** [comment]
It's strange how GCC managed to compile this without a warning.

**Comment by Dawoodoz** [comment]
Attempted fix in:
https://github.com/Dawoodoz/DFPSR/commit/cd33bdc055ec54db875f725fcb0322e06b53ef55
