### ISSUE TITLE
Incorrect forward declaration of VirtualMachine

### ISSUE THREAD

**Issue by mmozeiko** [Dawoodoz/DFPSR#14]
types.h forward declares it as class: https://github.com/Dawoodoz/DFPSR/blob/master/Source/DFPSR/api/types.h#L96
but it is actually a struct: https://github.com/Dawoodoz/DFPSR/blob/master/Source/DFPSR/machine/VirtualMachine.h#L261

This is not allowed, and for some compilers it will miscompile things like `MediaMachine(const std::shared_ptr<VirtualMachine>& machine)` - which sees only forward declaration of VirtualMachine: https://github.com/Dawoodoz/DFPSR/blob/master/Source/DFPSR/api/types.cpp#L49

**Comment by Dawoodoz** [comment]
Thanks, should be an easy fix.

**Comment by Dawoodoz** [comment]
Attempted fix in:
https://github.com/Dawoodoz/DFPSR/commit/cd33bdc055ec54db875f725fcb0322e06b53ef55
